name: "提交报错"
description: 上传未收录的报错类型
title: "📄[UPLOAD-CRASH] 请输入标题"
labels: [
  "报错提交"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "描述问题"
      description: 请简单描述您遇到的问题
      placeholder: 问题描述……
      render: bash
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "您正在进行的操作是？"
      description: 请详细描述报错发生时你正在做的事
      value: |
        1. 
        2. 
        3. 
        4. 出现报错
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "日志"
      description: 请将您的报错日志粘贴到此处
      placeholder: 日志...
      render: bash
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "操作系统"
      description: 您使用的操作系统是？
      multiple: false
      options:
        - Andriod
        - Windows
        - Linux
        - Mac
    validations:
      required: true
  - type: dropdown
    id: dropdown
    attributes:
      label: "官方 / libre"
      description: 您使用的是 官方分支 还是 libre 分支？
      multiple: false
      options:
        - 官方分支
        - libre分支
    validations:
      required: true
